### ISSUE TITLE
uploading a large (2+G) raster layer from either QGIS or the web UI time-outs connection

### ISSUE THREAD

**Issue by PeterPetrik** [MerginMaps/mergin#21]
connection timed out, timeout 300.00

```
[ERROR] [23] Error handling request /v1/project/push/chunk/181c0e85-5731-4dae-9487-13a9f27e5637/qmqx4lw3atj||Traceback (most recent call last):||  File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base_async.py", line 56, in handle||    self.handle_request(listener_name, req, client, addr)||  File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/ggevent.py", line 160, in handle_request||    addr)||  File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base_async.py", line 107, in handle_request||    respiter = self.wsgi(environ, resp.start_response)||  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2464, in __call__||    return self.wsgi_app(environ, start_response)||  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2450, in wsgi_app||    response = self.handle_exception(e)||  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1867, in handle_exception||    reraise(exc_type, exc_value, tb)||  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise||    raise value||  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app||    response = self.full_dispatch_request()||  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request||    rv = self.handle_user_exception(e)||  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception||    reraise(exc_type, exc_value, tb)||  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise||    raise value||  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request||    rv = self.dispatch_request()||  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request||    return self.view_functions[rule.endpoint](**req.view_args)||  File "/app/src/auth/__init__.py", line 41, in wrapped_func||    if not current_user or not current_user.is_authenticated:||  File "/usr/local/lib/python3.6/dist-packages/werkzeug/local.py", line 329, in __bool__||    return bool(self._get_current_object())||  File "/usr/local/lib/python3.6/dist-packages/werkzeug/local.py", line 307, in _get_current_object||    return self.__local()||  File "/usr/local/lib/python3.6/dist-packages/flask_login/utils.py", line 26, in <lambda>||    current_user = LocalProxy(lambda: _get_user())||  File "/usr/local/lib/python3.6/dist-packages/flask_login/utils.py", line 302, in _get_user||    current_app.login_manager._load_user()||  File "/usr/local/lib/python3.6/dist-packages/flask_login/login_manager.py", line 317, in _load_user||    return self.reload_user()||  File "/usr/local/lib/python3.6/dist-packages/flask_login/login_manager.py", line 279, in reload_user||    user = self.user_callback(user_id)||  File "/app/src/auth/__init__.py", line 97, in load_user||    return User.query.get(user_id)||  File "<string>", line 2, in get||  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/deprecations.py", line 390, in warned||    return fn(*args, **kwargs)||  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 933, in get||    return self._get_impl(ident, loading.load_on_pk_identity)||  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 945, in _get_impl||    execution_options=self._execution_options,||  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2800, in _get_impl||    load_options=load_options,||  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/loading.py", line 535, in load_on_pk_identity||    bind_arguments=bind_arguments,||  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 1669, in execute||    conn = self._connection_for_bind(bind, close_with_result=True)||  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 1520, in _connection_for_bind||    engine, execution_options||  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind||    conn = bind.connect()||  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 3096, in connect||    return self._connection_cls(self, close_with_result=close_with_result)||  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 92, in __init__||    else engine.raw_connection()||  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 3175, in raw_connection||    return self._wrap_pool_connect(self.pool.connect, _connection)||  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 3142, in _wrap_pool_connect||    return fn()||  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool/base.py", line 301, in connect||    return _ConnectionFairy._checkout(self)||  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool/base.py", line 761, in _checkout||    fairy = _ConnectionRecord.checkout(pool)||  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool/base.py", line 419, in checkout||    rec = pool._do_get()||  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool/impl.py", line 137, in _do_get||    code="3o7r",||sqlalchemy.exc.TimeoutError: QueuePool limit of size 2 overflow 10 reached, connection timed out, timeout 300.00 (Background on this error at
```

**Comment by varmar05** [comment]
There were multiple fixes for sync process done in 2023.2.0, so this should not be an issue anymore.
However download of large zip project archives was limited to certain size (around 1 GB)
